spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vault_db
    username: root
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:vault-pfe-2025-built-with-passion-never-stop}
  expiration-ms: 900000
  refresh-expiration-ms: 604800000

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:19006
    - http://localhost:8081
    - http://localhost
    - http://localhost:80
    - http://10.0.2.2:19006
    - http://192.168.0.95:19006
    - http://192.168.0.95:8081

logging:
  level:
    com.thevault: DEBUG
    org.springframework.security: DEBUG
