INSERT INTO brand_references (name, slug, tier, display_order) VALUES
--LUXURY 
('Chanel',            'chanel',            'LUXURY',        1),
('Louis Vuitton',     'louis-vuitton',     'LUXURY',        2),
('Hermès',            'hermes',            'LUXURY',        3),
('Dior',              'dior',              'LUXURY',        4),
('Givenchy',          'givenchy',          'LUXURY',        5),
('Saint Laurent',     'saint-laurent',     'LUXURY',        6),
('Balenciaga',        'balenciaga',        'LUXURY',        7),
('Bottega Veneta',    'bottega-veneta',    'LUXURY',        8),
('Prada',             'prada',             'LUXURY',        9),
('Gucci',             'gucci',             'LUXURY',        10),
('Versace',           'versace',           'LUXURY',        11),
('Fendi',             'fendi',             'LUXURY',        12),
('Valentino',         'valentino',         'LUXURY',        13),
('Celine',            'celine',            'LUXURY',        14),
('Loewe',             'loewe',             'LUXURY',        15),
('Khaite',            'khaite',            'LUXURY',        16),
('The Row',           'the-row',           'LUXURY',        17),
('Jacquemus',         'jacquemus',         'LUXURY',        18),
('Lanvin',            'lanvin',            'LUXURY',        19),
('Mugler',            'mugler',            'LUXURY',        20),
('AMI',               'ami',               'LUXURY',        21),
('Dries Van Noten',   'dries-van-noten',   'LUXURY',        22),
('Missoni',           'missoni',           'LUXURY',        23),
('Vetements',         'vetements',         'LUXURY',        24),
('Maison Margiela',   'maison-margiela',   'LUXURY',        25),
('Issey Miyake',      'issey-miyake',      'LUXURY',        26),
('Comme des Garçons', 'comme-des-garcons', 'LUXURY',        27),

-- CONTEMPORARY
('Ganni',             'ganni',             'CONTEMPORARY',  30),
('Toteme',            'toteme',            'CONTEMPORARY',  31),
('Aries',             'aries',             'CONTEMPORARY',  32),
('ERL',               'erl',               'CONTEMPORARY',  33),
('Casablanca',        'casablanca',        'CONTEMPORARY',  34),
('Acne Studios',      'acne-studios',      'CONTEMPORARY',  35),
('Max Mara',          'max-mara',          'CONTEMPORARY',  36),
('Isabel Marant',     'isabel-marant',     'CONTEMPORARY',  37),
('Sandro',            'sandro',            'CONTEMPORARY',  38),
('A.P.C.',            'apc',               'CONTEMPORARY',  39),
('Nanushka',          'nanushka',          'CONTEMPORARY',  40),
('Zimmermann',        'zimmermann',        'CONTEMPORARY',  41),
('Self Portrait',     'self-portrait',     'CONTEMPORARY',  42),
('Rotate',            'rotate',            'CONTEMPORARY',  43),

-- STREETWEAR
('Kith',              'kith',              'STREETWEAR',    50),
('Daily Paper',       'daily-paper',       'STREETWEAR',    51),
('Carhartt WIP',      'carhartt-wip',      'STREETWEAR',    52),
('adidas',            'adidas',            'STREETWEAR',    53),
('Nike',              'nike',              'STREETWEAR',    54),
('New Balance',       'new-balance',       'STREETWEAR',    55),
('Stüssy',            'stussy',            'STREETWEAR',    56),
('Raf Simons',        'raf-simons',        'STREETWEAR',    57),

-- HIGH STREET 
('Zara',              'zara',              'HIGH_STREET',   60),
('Massimo Dutti',     'massimo-dutti',     'HIGH_STREET',   61),
('COS',               'cos',               'HIGH_STREET',   62),
('Arket',             'arket',             'HIGH_STREET',   63),
('& Other Stories',   'and-other-stories', 'HIGH_STREET',   64),
('Mango',             'mango',             'HIGH_STREET',   65),
('Reiss',             'reiss',             'HIGH_STREET',   66),

-- SUSTAINABLE 
('Pangaia',           'pangaia',           'SUSTAINABLE',   70),
('Stella McCartney',  'stella-mccartney',  'SUSTAINABLE',   71),
('Veja',              'veja',              'SUSTAINABLE',   72),
('Organic Basics',    'organic-basics',    'SUSTAINABLE',   73),

-- VINTAGE
('By Rotation',       'by-rotation',       'VINTAGE',       80),
('Depop Vintage',     'depop-vintage',     'VINTAGE',       81);
