INSERT INTO service_catalog (slug, name, tagline, description, note, display_order) VALUES
('styling-edit',        'The Styling Edit',       'Bespoke Looks. Instant Access.',                'Selections tailored around your lifestyle, occasions, and signature look. Your Vault Image Consultant refines each edit, linked for seamless shopping.',                                     'Private in-person consultations available upon request.', 1),
('seasonal-wardrobe',   'The Seasonal Wardrobe',  'Tailored to your rhythm. Always in season.',    'Looks perfectly attuned to the current season, designed for your most refined occasions. Each month, your Vault Image Consultant selects every piece with precision and care.',            NULL,                                                      2),
('holiday-wardrobe',    'The Holiday Wardrobe',   'Your travel Attire, Delivered in Distinction.', 'Your suitcase, meticulously packed and thoughtfully styled to align with your itinerary and every iconic moment in between.',                                                             'Holiday styling available. Instantly shop your curated looks.', 3),
('dressing-room',       'The Dressing Room',      'Your Personal Styling Lab',                     'Rediscover, restyle, and elevate the pieces you already own. Upload your wardrobe to explore endless outfit possibilities.',                                                               'Personalized styling from your own wardrobe, with professional guidance.', 4),
('styling-suite-pro',   'The Styling Suite Pro',  'Executive Image. Elevated Impact.',             'White-glove styling and bespoke consulting for executives, talent, and high-profile professionals.',                                                                                       'A refined image for every occasion that demands distinction.', 5),
('wishlist',            'The Wishlist',            'Track it. Prioritize it. Own it.',              'Never forget what you love — your personalized shopping list with real-time insights into your fashion habits.',                                                                           'Your personal fashion tracker with instant alerts and analytics.', 6),
('private-rental',      'Private Rental',          'Lend. Buy. Sell. Borrow. Belong.',              'Share your luxury wardrobe or discover coveted pieces within the Vault community.',                                                                                                        'A private exchange connecting you to rare and exceptional wardrobe treasures.', 7),
('conciergerie',        'The Conciergerie',        'Your World, On Demand.',                        'From reservations to seamless travel arrangements, every detail of your world is handled with precision and discretion.',                                                                  'Your concierge, on speed dial.', 8),
('journal',             'The Journal',             'Premier Fashion Source',                        'Your go-to guide to elegance and expert style insights. Uncover the latest trends, timeless classics, and curated stories.',                                                               'Inspiration and guidance for discerning taste.', 9),
('image-consultant-lab','Image Consultant Lab',    'Global Talent. Unique Style.',                  'Connect with clients worldwide through live sessions, offering personalized outfit guidance, styling expertise, and tailored shopping advice.',                                             'Grow your influence. Elevate their experience.', 10);
